name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: configure
        run: ./configure
      - name: install gcd
        run: |
          cd gcd
          make install
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: configure gcd
        run: |
          cd gcd
          make add-mapping SHORTCUT=sockery DIR=${{ github.workspace }}/sockery
      - name: build & test
        run: |
          eval "$(~/.local/bin/gcd sockery)"
          just actions-build
          valgrind --leaks-check=full -s ./artifacts/sockery
      - name: clean
        run: just distclean
