name: release
on: push

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: install V
        run: |
          sudo apt install -y git wget gcc make
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make
          sudo ./v symlink

      # Use the same config script as ci.yml
      - name: configure
        run: ./configure

      - name: fill assets
        run: just fill-assets
      - name: download assets
        run: just download-assets
