name: release
on: push

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        run: actions/checkout@v6
      - name: install V
        run: |
          sudo apt-get update
          sudo apt install git wget
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make
      # Use the same config script as ci.yml
      - name: configure
        run: ./configure
      - name: fill assets
        run: just fill-assets
      - name: download assets
        run: just download-assets
